/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package doublependulum;

/**
 *
 * @author Kyungbin
 */
public class Selection extends javax.swing.JFrame {

    /**
     * Creates new form Selection
     */
    public Selection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        createButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kyungbin\\Downloads\\GraphicDesign (1).png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSpinner1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(30, 30, 100, 5));
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSpinner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner1MouseClicked(evt);
            }
        });
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 90, 40));

        jSpinner2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(30, 30, 100, 5));
        jSpinner2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSpinner2.setFocusTraversalPolicyProvider(true);
        jSpinner2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner2MouseClicked(evt);
            }
        });
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 90, 40));

        jSpinner3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSpinner3.setModel(new javax.swing.SpinnerListModel(new String[] {"Pink ", "Blue ", "Black ", "White"}));
        jSpinner3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSpinner3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner3MouseClicked(evt);
            }
        });
        getContentPane().add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 100, 40));

        jSpinner4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(30, 30, 100, 5));
        jSpinner4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSpinner4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner4MouseClicked(evt);
            }
        });
        getContentPane().add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 90, 40));

        jSpinner5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(30, 30, 100, 5));
        jSpinner5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSpinner5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner5MouseClicked(evt);
            }
        });
        getContentPane().add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 90, 40));

        createButton.setBackground(new java.awt.Color(255, 102, 102));
        createButton.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Create!");
        createButton.setBorder(null);
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 160, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kyungbin\\Downloads\\GraphicDesign (2).png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -50, 610, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        
    }//GEN-LAST:event_createButtonActionPerformed

    private void jSpinner4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner4MouseClicked
        
        
    }//GEN-LAST:event_jSpinner4MouseClicked

    private void jSpinner2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner2MouseClicked
        
        
    }//GEN-LAST:event_jSpinner2MouseClicked

    private void jSpinner1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseClicked
        
    }//GEN-LAST:event_jSpinner1MouseClicked

    private void jSpinner5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner5MouseClicked
        
    }//GEN-LAST:event_jSpinner5MouseClicked

    private void jSpinner3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner3MouseClicked
    }//GEN-LAST:event_jSpinner3MouseClicked

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        int mass1 = (Integer) jSpinner4.getValue();
        int mass2 = (Integer) jSpinner2.getValue();
        int mass3 = (Integer) jSpinner1.getValue();
        int mass4 = (Integer) jSpinner5.getValue();
        String color = (String) jSpinner3.getValue();
        System.out.println(mass1 + " " + mass2 + " " + mass3 + " " + mass4 + " "+ color );
        dispose();
        new DoublePendulum().setVisible(true);
        
        
        
        
    }//GEN-LAST:event_createButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selection().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton createButton;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JSpinner jSpinner1;
    public javax.swing.JSpinner jSpinner2;
    public javax.swing.JSpinner jSpinner3;
    public javax.swing.JSpinner jSpinner4;
    public javax.swing.JSpinner jSpinner5;
    // End of variables declaration//GEN-END:variables
}
